server:
  port: 8085

spring:
  application:
    name: payment-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/payment_db
    username: payment_user
    password: payment_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          max-interval: 10000ms
          multiplier: 2.0

payment:
  gateways:
    stripe:
      api-key: sk_test_fake_key
      webhook-secret: whsec_fake_secret
    paypal:
      client-id: fake_client_id
      client-secret: fake_client_secret
      mode: sandbox
  
  processing:
    timeout-seconds: 30
    retry-attempts: 3
    async-processing: true

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    generate-unique-process-engine-name: false
    database:
      schema-update: true
    auto-deployment-enabled: true
    deployment-resource-pattern: classpath*:*.bpmn
