spring:
    application:
        name: cart-service
    cassandra:
        contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS:cassandra}
        port: ${SPRING_CASSANDRA_PORT:9042}
        keyspace-name: ${SPRING_CASSANDRA_KEYSPACE_NAME:cart_service}
        schema-action: create_if_not_exists
        local-datacenter: ${SPRING_CASSANDRA_LOCAL_DATACENTER:datacenter1}
    rabbitmq:
        host: ${SPRING_RABBITMQ_HOST:localhost}
        port: 5672
        username: ${SPRING_RABBITMQ_USERNAME:admin}
        password: ${SPRING_RABBITMQ_PASSWORD:password}
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
            - org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration
    datasource:
        # H2 в памяти для Camunda
        url: jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: sa
        password: ""

server:
    port: 8080

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    generate-unique-process-engine-name: true
    database:
      schema-update: true
    auto-deployment-enabled: true
    deployment-resource-pattern: classpath*:*.bpmn
